services:
  dummy:
    image: busybox
    command: tail -f /dev/null
  app:
    build: .
    command: go run .
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
